### ISSUE TITLE
Broken `gopass` support for `pass` backend

### ISSUE THREAD

**Issue by lsowen** [99designs/aws-vault#667]
As of commit https://github.com/99designs/aws-vault/commit/ecd1502a77be8f8ea456f0229e780615fe6dbe44 , support for using gopass (https://github.com/gopasspw/gopass) via `AWS_VAULT_PASS_CMD=gopass` seems to be broken.

The issue is that `gopass insert -m -f oidc:https:/d-<REDACTED>.awsapps.com/start` used to store the OIDC token errors with "Error: Usage: gopass insert name".

This is because the colon in the "secret name" triggers gopass to handle that as a key/value field (https://github.com/gopasspw/gopass/pull/790), so gopass doesn't see a "secret name", just a single k/v pair.

Would it be possible to either:
1. Disable OIDC token caching; or
2. Change the naming convention of the secret?

**Comment by rngtng** [comment]
hey @lsowen - did you solve it in meanwhile? I just can't was-vault & go pass working together. I see the session credentials are stored in (go)pass, but apparently not read as I'm asked to authorise over and over again :(

**Comment by lsowen** [comment]
I did, this issue was fixed in newer versions of gopass (they reverted the colon handling).

However, I did have another issue where gopass tries to be clever with storing/showing the passwords which breaks aws-vault, something like:

```bash
$ gopass show test:test
Password: hello
$ gopass show --password test:test
hello
```

I'm not sure if you are running into this same issue or not, but how I solved it was using the following:

1. Create the following environment variables:
```bash
AWS_VAULT_PASS_CMD=aws-vault-gopass
AWS_VAULT_BACKEND=pass
```
2. Add the shell script `aws-vault-gopass` somewhere on your `$PATH`:
```bash
#!/bin/bash

ARGS=( "$@" )

if [ "${ARGS[0]}" == "insert" ]
then
    gopass ${ARGS[@]}
elif [ "${ARGS[0]}" == "show" ]
then
    gopass show --password "${ARGS[1]}"
elif [ "${ARGS[0]}" == "rm" ]
then
    gopass ${ARGS[*]}
fi
```

This overrides the "show" command so that only the password is returned.

**Comment by rngtng** [comment]
Thanks for you feedback. Unfortunately it didn't solve my problem. I think it's related to using was-vault with SSO. I used your script and just printed the aws-vault commands. There I could see that session is inserted into store:

```
insert -m -f aws-vault/oidc:https:/....awsapps.com/start
insert -m -f aws-vault/sso.GetRoleCredentials,d.....A,1637790867
```
But I never see a pass command where those get read. Interestingly calling `aws-vault list` after sign-in doesn't show any open sessions/credentials. But when using macOS keychain this all works :( Any ideas? Thx

**Comment by lsowen** [comment]
if you run the `gopass list` do you see the `aws-vault/...` entries listed?   And if not, does running the `gopass insert ...` commands manually succeed or fail?

**Comment by rngtng** [comment]
yes, both is the case: `gopass list` shows entires and `gopass insert` succeeds. Only weird part is that I never see a `gopass show` command executed. Maybe SSO doesn't support pass backend? Are you using SSO?

**Comment by lsowen** [comment]
I am, yes

**Comment by rngtng** [comment]
Hm ok weird. Need to debug it more. Thanks the feedback…

**Comment by rngtng** [comment]
On more question: in figured AWS_VAULT_PASS_PASSWORD_STORE_DIR needs to be set to make the backend work at all, strange that even a random path is ok. Is this same for you?
I assume you‘re running latest AWS-vault and gopass? Do you have multiple stores in gopass setup too? Thx

**Comment by rngtng** [comment]
YES! I finally got it working. Reason was due to two stores:
1.  `~/.password-store` (default)
2.  `~/.password-store-awsvault` (vault)

and my initial config:
```
export AWS_VAULT_BACKEND=pass
export AWS_VAULT_PASS_CMD=aws-vault-pass
export AWS_VAULT_PASS_PASSWORD_STORE_DIR=~/.password-store-awsvault
export AWS_VAULT_PASS_PREFIX=vault
```

This worked writing, but never reading. As said is didn't even see `aws-vault list` calling `aws-vault-pass`. Looks like the missing `vault` folder is a problem and `aws-vault` does a direct directory inspection of  `AWS_VAULT_PASS_PASSWORD_STORE_DIR`. Fix was to hardcode the `AWS_VAULT_PASS_PREFIX` into your script and to not set the variable. Strictly spoken `vault` is not a prefix but the name of the store, so it makes sense. And it works! thanks the effort!
